export type { CreateAdGroupAdInput } from "./ad-group-ads.ts";
export { adGroupAds } from "./ad-group-ads.ts";
export type { CreateAdGroupInput } from "./ad-groups.ts";
export { adGroups } from "./ad-groups.ts";
export { ads } from "./ads.ts";
export type { CreateCampaignBudgetInput } from "./campaign-budgets.ts";
export { campaignBudgets } from "./campaign-budgets.ts";
export type { CreateCampaignInput } from "./campaigns.ts";
export { campaigns } from "./campaigns.ts";
export type { Customer } from "./customer.ts";
export { createCustomer } from "./customer.ts";
export type { QueryState, RowOf } from "./gaql/index.ts";
export { BoundQueryBuilder, gaql, gaqlFactory, QueryBuilder } from "./gaql/index.ts";
export type { Ref } from "./types.ts";
export { resolveRef } from "./types.ts";
