{
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        }
      }
    }
  },
  "id": "youtubeAnalytics:v2",
  "basePath": "",
  "canonicalName": "YouTube Analytics",
  "revision": "20260803",
  "title": "YouTube Analytics API",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "name": "youtubeAnalytics",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "servicePath": "",
  "resources": {
    "reports": {
      "methods": {
        "query": {
          "id": "youtubeAnalytics.reports.query",
          "flatPath": "v2/reports",
          "description": "Retrieve your YouTube Analytics reports.",
          "path": "v2/reports",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    },
    "groups": {
      "methods": {
        "delete": {
          "description": "Deletes a group.",
          "path": "v2/groups",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "id": "youtubeAnalytics.groups.delete"
        },
        "insert": {
          "id": "youtubeAnalytics.groups.insert",
          "flatPath": "v2/groups",
          "description": "Creates a group.",
          "path": "v2/groups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "list": {
          "id": "youtubeAnalytics.groups.list",
          "path": "v2/groups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "flatPath": "v2/groups"
        },
        "update": {
          "id": "youtubeAnalytics.groups.update",
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Modifies a group. For example, you could change a group's title."
        }
      }
    },
    "groupItems": {
      "methods": {
        "insert": {
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Creates a group item.",
          "id": "youtubeAnalytics.groupItems.insert"
        },
        "delete": {
          "id": "youtubeAnalytics.groupItems.delete",
          "description": "Removes an item from a group.",
          "path": "v2/groupItems",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groupItems"
        },
        "list": {
          "path": "v2/groupItems",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Returns a collection of group items that match the API request parameters.",
          "flatPath": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.list"
        }
      }
    }
  },
  "version": "v2",
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "description": "Retrieves your YouTube Analytics data."
}
